### PR TITLE
geo + census features; matplotlib inline rendering fix

### PR DESCRIPTION
**Pull request by dmedv**
Incorporating packages from https://github.com/sciserver/sciserver-images/tree/develop/geo and https://github.com/sciserver/sciserver-images/tree/develop/census

A couple of packages could not be installed with conda because of Python version incompatibility, so I installed them with pip. 

I introduced version tags to make it easier to keep track of fixes and changes. For example, the latest geo image is tagged `dockerregistry:443/sciserver-essentials:1.1-geo`.

### CODE REVIEW

**Review by glemson — APPROVED** [review]

**Review by amitschang — COMMENTED** [review]
Wouldn't version in the filename make it *harder* to compare changes?

**Comment by dmedv** [comment]
@amitschang I haven't given it much thought, to be honest, but how else would you organize incremental Dockerfiles? I mean v1.1 is not just an update of Dockerfile v1.0, it's a new Dockerfile that uses v1.0 image (or, more accurately, it uses **an** image built using the v1.0 Dockerfile... which is a whole new problem).

**Comment by amitschang** [comment]
Oh, so we would never edit 1.0, and only make 1.1 that is FROM 1.0? Doesn't seem that sustainable, but I could be missing the workflow. 

I am all for tagging versions, but it does seem somewhat independent of the Dockerfile that created it. 

In any case, maybe just something to think about, but I don't mean to block this going out.

**Comment by dmedv** [comment]
The problem is that changing the 1.0 Dockerfile and rebuilding it will likely result in a lot more changes than is recorded in the Dokerfile, because of uncontrolled (uncontrollable?) package updates. So, we don't wan't to rebuild the base image unless absolutely necessary. The old Dockerfiles are there mainly for reference, so that we could at least understand what we were doing in the beginning, but I think the safest way to update an image is to apply another layer. I am aware that there are problems with this approach, but so far I haven't found another approach that is complete free of any problems, so we might as well try this one for some time, and change it if indeed becomes unsustainable. Of course, if anyone has better ideas, please share.

**Comment by amitschang** [comment]
Yeah, what you say makes sense, and is certainly exacerbated by providing an OS like environment where one cannot really test for sure for incompatibilities (since we don't know all the uses).

**Review by amitschang — APPROVED** [review]

**Pull request merged**
