### PR TITLE
Add libGL system library

### PR DESCRIPTION
**Pull request by dmedv**

### CODE REVIEW

**Review by amitschang — APPROVED** [review]

**Review by glemson — APPROVED** [review]
I trust this update is ok, as long as it now allows users to install openCV.

**Comment by dmedv** [comment]
@glemson I did check that opencv can be installed and imported w/o errors, but nothing more. Perhaps I should try some more meaningful tests, or wait until that student responds.

**Comment by glemson** [comment]
Seems the student replied and can install opencv.
May try to install one of these other vis libraries that before failed.

**Comment by dmedv** [comment]
`ipygany` works

```
mamba install -y -c conda-forge ipygany vtk
mamba install -y -c conda-forge -n base ipygany 
```

**Comment by glemson** [comment]
Did you try using it as well?
I believe I had problems when importing vtk.

**Comment by dmedv** [comment]
@glemson You mean importing vtk as a python package? I don't think you need to do that explicitly. Anyway, I installed ipygany and tested the example notebook from their git repo, and it worked.

**Comment by glemson** [comment]
before I got
ImportErrorTraceback (most recent call last)
<ipython-input-9-7c7f66f02cd3> in <module>
----> 1 import vtk

~/miniconda3/envs/py38/lib/python3.8/site-packages/vtk.py in <module>
     28     import importlib
     29     # import vtkmodules.all
---> 30     all_m = importlib.import_module('vtkmodules.all')
     31 
     32     # import vtkmodules

~/miniconda3/envs/py38/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~/miniconda3/envs/py38/lib/python3.8/site-packages/vtkmodules/all.py in <module>
     21 from .vtkRenderingFreeType import *
     22 from .vtkRenderingSceneGraph import *
---> 23 from .vtkRenderingVtkJS import *
     24 from .vtkIOExport import *
     25 from .vtkWebGLExporter import *

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Now it works.

**Pull request merged**
