### PR TITLE
Added jupyterlab extensions

### PR DESCRIPTION
**Pull request by mtaghiza**
Currently testing on SciServer Essentials (Test) image, but some extensions might not be fully working.

JUPYTER LAB extensions added:

-JupyterLab variable Inspector: https://github.com/lckr/jupyterlab-variableInspector  DONE

-jupyterlab html: https://github.com/mflevine/jupyterlab_html  already included in jupyterlab 3.0

-jupyter-dash: https://github.com/plotly/jupyter-dash   DONE

-voila: https://github.com/voila-dashboards/voila DONE 

-bokeh: https://github.com/bokeh/jupyter_bokeh DONE 

-jupyterlab-latex: https://github.com/jupyterlab/jupyterlab-latex  not supported for jupyterlab 3.0 yet

-jupyterlab-git  https://github.com/jupyterlab/jupyterlab-git DONE

-jupyterlab-drawio: https://github.com/QuantStack/jupyterlab-drawio  DONE

-spellchecker(for markdown cells): https://github.com/jupyterlab-contrib/spellchecker DONE

-jupyterlab-system-monitor https://github.com/jtpio/jupyterlab-system-monitor DONE

-jupyterlab_code_formatter: https://github.com/ryantam626/jupyterlab_code_formatter DONE

-jupyterlab-hdf5: https://github.com/jupyterlab/jupyterlab-hdf5  No Jupyterlab 3.0 support yet

-dask: https://github.com/dask/dask-labextension  Mitya already has exposed this dask dashboard through a separate URL

-Code snippets: https://github.com/jupytercalpoly/jupyterlab-code-snippets creates a folder called snippets

-ITK viewer: https://github.com/InsightSoftwareConsortium/itkwidgets No Jupyterlab 3.0 support yet

-jupyterlab-cell-flash : https://github.com/jtpio/jupyterlab-cell-flash  DONE

-jupyterlab-tabular-data-editor: https://github.com/jupytercalpoly/jupyterlab-tabular-data-editor DONE

-gator : https://github.com/mamba-org/gator DONE

-ipympl: https://github.com/matplotlib/ipympl DONE

-networkx: https://github.com/networkx/networkx DONE

-ipyvolume: https://github.com/maartenbreddels/ipyvolume No Jupyterlab 3.0 support yet

### CODE REVIEW

**Comment by mtaghiza** [comment]
Note: one first change from sciserver essentials 2.2 version is the upgrade to JupyterLab 3.0

**Comment by dmedv** [comment]
I think installing jupyter/jupyterlab plugins in the py38 environment (like `jupyterlab_code_formatter`) will have no effect, because jupyter is running in the base environment.

**Comment by dmedv** [comment]
`pip install` should be used with the `--no-cache-dir` option to minimize the Docker image size. Also, run `conda clean -y --all` after installing conda/mamba packages, for the same reason (make sure you do it in the same RUN statement, otherwise Docker will create a new layer, and cleanup won't have any effect).

**Comment by dmedv** [comment]
I haven't gone through everything, but what I have tested seems to work, and the Dockerfile makes sense.

**Review by dmedv — APPROVED** [review]

**Comment by glemson** [comment]
If all these are jupyterlab extension (true?) would it make sense to start this image in jupyterlab as well iso classic jupyter?

**Comment by glemson** [comment]
diagram and git work nicely, though it would be nice if it were possible to see files like .gitignore in the left-side file browser panel. Is that possible? Desired by others?

**Comment by mtaghiza** [comment]
> If all these are jupyterlab extension (true?) would it make sense to start this image in jupyterlab as well iso classic jupyter?

Some work also in classic Jupyter. But starting directly with JupyterLab could be better, as most of users could be already familiar with it, and prefer it over the classic version.

**Comment by mtaghiza** [comment]
> diagram and git work nicely, though it would be nice if it were possible to see files like .gitignore in the left-side file browser panel. Is that possible? Desired by others?

One can edit the .gitignore file with the top menu:   Git -> Open .gitignore

**Comment by glemson** [comment]
I use a .private folder to store some "private" things. I would like being able to see it as well, but can work around it.
Otoh I don't mind *not* seeing .ipynb_checkpoints everywhere.
A toggle option would be nice if it exists.

**Comment by mtaghiza** [comment]
> I use a .private folder to store some "private" things. I would like being able to see it as well, but can work around it. Otoh I don't mind *not* seeing .ipynb_checkpoints everywhere. A toggle option would be nice if it exists.

We can add a setting when Jupyter starts to make hidden files visible, but seems one cannot toggle that afterwards. 
There is currently an active pull request to allow live toggling, so we could wait for it instead:
 https://github.com/jupyterlab/jupyterlab/pull/10769

**Comment by mtaghiza** [comment]
Feel free to suggest additions/removal of features.

Newly installed features:

View and edit CSVs: 
	https://github.com/jupytercalpoly/jupyterlab-tabular-data-editor
Create and insert code snippets: 
	https://github.com/jupytercalpoly/jupyterlab-code-snippets
Create dashboard with components dragged from an executed notebook.
	https://github.com/jupytercalpoly/jupyterlab-interactive-dashboard-editor
Shows date and time span of running cell: 
	https://github.com/deshaw/jupyterlab-execute-time
Syntax checker and code completion:
        https://github.com/krassowski/jupyterlab-lsp
Download directory as compressed file:
	https://github.com/jupyterlab-contrib/jupyter-archive
Revert notebook back to previous saved versions: 
	https://github.com/timkpaine/jupyterlab_autoversion
Small widgets around cell to run/delete/format cell
	https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar
Run parametrized notebooks:
	https://github.com/nteract/papermill
HDF5 file viewer:
	https://github.com/jupyterlab/jupyterlab-hdf5
Right click on script/file and run with several executors:
	https://github.com/gavincyi/jupyterlab-executor
3-D visualization:	
	https://github.com/maartenbreddels/ipyvolume


These extensions did not fully work or interfered with other extensions. Had to remove them, but could be included in a next version of this image once their problems are fixed:

https://github.com/jupyterlab/jupyterlab-latex
https://github.com/lux-org/lux
https://github.com/mwouts/jupytext/
https://github.com/willkessler/jupyterterminals
https://github.com/silx-kit/jupyterlab-h5web
https://github.com/rapidsai/jupyterlab-nvdashboard
https://github.com/quigleyj97/jupyterlab-spreadsheet

Some interesting to look at :

https://github.com/ml-tooling/ml-workspace
https://github.com/kiteco/jupyterlab-kite   
https://github.com/codota/tabnine-jupyterlab
https://github.com/elyra-ai/elyra
https://github.com/lgpage/nbtutor
https://github.com/epi2me-labs/jupyterlab-code-cell-collapser
https://github.com/epi2me-labs/jupyterlab-play-cell-button
https://github.com/epi2me-labs/jupyterlab-autorun-cells
https://github.com/jpmorganchase/jupyter-fs
https://github.com/pbugnion/jupyterlab-sql
https://github.com/aquirdTurtle/Collapsible_Headings
https://github.com/cytoscape/ipycytoscape
https://github.com/parente/jupyterlab-quickopen
https://github.com/remborg/autoplay
https://github.com/mwakaba2/jupyterlab-notifications
https://github.com/ShopRunner/jupyter-notify
https://github.com/jpmorganchase/jupyterlab_templates


Resources:
https://github.com/ml-tooling/best-of-jupyter
https://github.com/ml-tooling/best-of-ml-python
https://github.com/mauhai/awesome-jupyterlab
https://github.com/markusschanta/awesome-jupyter
https://github.com/quobit/awesome-python-in-education#jupyter
https://neptune.ai/blog/jupyterlab-extensions-for-machine-learning
https://towardsdatascience.com/awesome-jupyterlab-extensions-90c2d64d244

**Comment by mtaghiza** [comment]
Will merge and push to prod if there are no more petitions.

**Comment by glemson** [comment]
what are consequences of pushing this to prod? is the image automatically created and added to nexus(?) ?

**Review by glemson — APPROVED** [review]
I think better for Mitya and Arik to look at the details here. I will try out the debugging when I have time, but that is for me not a showstopper.

**Comment by mtaghiza** [comment]
I'll then merge next week to allow for more testing or comments.

**Comment by glemson** [comment]
Is there somewhere a manual/explanation about the new features and how to use them?
Also, can I turn (some of) them off?

**Review by amitschang — APPROVED** [review]
Not the biggest fan of uninstall in the image def, but I guess it is a lot simpler to start from something like sciserver-essentails than go fresh here. Would this be made available as sciserver-essentials-2.4 in all domains?

**Review by glemson — COMMENTED** [review]
when using Git > Open Git Repository in Temrinal, I get a terminal with 
```
(py38) [idies@698ee470bb1e ~]$ cd "Storage/gerard/persistent/GIT/boom"
bash: cd: Storage/gerard/persistent/GIT/boom: No such file or directory
```

**Comment by glemson** [comment]
> ... Would this be made available as sciserver-essentials-2.4 in all domains? 

I think this should indeed not replace our current essentials. I think there are quite some new features here that users need to be informed about and they may want the choice to not have them available.

**Comment by mtaghiza** [comment]
As I mentioned above, feel free to suggest a list of features to disable (they are all enabled, so that you can see/test them).
Most of them can be disabled/enabled in the Advanced Settings Editor under the Settings tab, but that is not really user friendly. We can have the intrusive features disabled by default, and show in the documentation how to enable/use them. 
The non-intrusive/invisible additions can be explained in the documentation and left enabled, in the same way it has been the case for previous versions of this image (sciserver-essentials).

**Comment by glemson** [comment]
I don't think I should be the only one to do so. I wonder if we can ask our users to try out the new image and give feedback on what they like or don't like. so let's keep it with all bells and whistles, but as a separate image next to the existing essentials one, not have it replace it. 
and sorry if I missed this in the past, but do I understand correctly there is already documentation for these new features? apart from the ones above in this PR?

**Comment by mtaghiza** [comment]
(actually was thinking on updating the older documentation on https://www.sciserver.org/compute-images/)

Some disruptive features that could be disabled are those showing in/around the notebook cell (e.g., the syntax highlighting, enhanced-cell-toolbar, execution time, color flash after execution). But lets first wait for more comments.

**Comment by amitschang** [comment]
Sorry, should have made some comments earlier. My two cents are that there are too many half-baked features in this and that we should refrain from defaulting to things that we cannot or will not support to some extent. Things like the code-cell timing seem a good idea to have as the default, but several others might cause more trouble than good.

For example, the git features in this seem less than stable (sometimes diffs don't render, the repo side panel can be confusing as to what the context is), and we don't really have a reliable way to populate the git config at the moment (and have it remembered).

Another example is the snippets. I really like the idea of having snippets, but other than a panel and a couple of defaults this doesn't represent a strategy for managing them. Should we connect it to some volume of curated snippets? Or can we go by url? Is this just everyone for themselves, in which case seems like they would not preserve over containers.

I'm probably in the minority here, but I am of the opinion that we should rely less on Jupyter's fancy features and focus more on tighter integrations with SciServer and they way that works. Once we have such an integration, then some jupyter plugins may complement that well.

**Pull request merged**
