### PR TITLE
Update JupyterLab and install data format libraries

### PR DESCRIPTION
**Pull request by dmedv**
NAOJ wants to use JupyterLab 3.0, so I thought it would make sense to update the Essentials image.
I also added some data format libraries for handling multidimensional arrays that would be useful for a wide range of applications including oceanography, climatology and meteorology: NetCDF4, HDF5, Zarr, Xarray.

### CODE REVIEW

**Comment by glemson** [comment]
Is there a test installation already?
And is this going to be an update of 2.0, or are you creating a separate 2.1 image?
I'd prefer the former, unless you can give reasons why people might prefer the choice for 2.0 over 2.1?

**Comment by dmedv** [comment]
An update of 2.0. I'm not going to change the name and description of the image. The 2.1 tag is just for internal reference.
I can deploy it separately for testing though.

**Comment by glemson** [comment]
Test installation?

**Comment by dmedv** [comment]
Deployed as SciServer Essentials 2.1 for testing (not publicly visible).

**Comment by dmedv** [comment]
I'd like to add the updated SciScript with Dask features too (once @mtaghiza approves the PR https://github.com/sciserver/SciScript-Python/pull/14).

**Comment by mtaghiza** [comment]
> Is there a test installation already?
> And is this going to be an update of 2.0, or are you creating a separate 2.1 image?
> I'd prefer the former, unless you can give reasons why people might prefer the choice for 2.0 over 2.1?

What is going to be the policy for this? If the version of the internal code of the image changes, should the image name stay the same, as seen from the user point of view? If so, they might create 2 container from the same image name, and some of their code could run in the older container but fail on the updated one.

**Comment by dmedv** [comment]
@mtaghiza I think minor updates like this are ok, otherwise we'll end up with a ton of different images.

**Comment by mtaghiza** [comment]
I would tend to think that as well, although updating versions might sometimes cause unforeseen consequences upstream, even for minor updates.

**Review by mtaghiza — APPROVED** [review]

**Review by amitschang — APPROVED** [review]

**Review by glemson — APPROVED** [review]
would like a short discussion on Manu's concerns.

**Comment by amitschang** [comment]
> What is going to be the policy for this? If the version of the internal code of the image changes, should the image name stay the same, as seen from the user point of view? If so, they might create 2 container from the same image name, and some of their code could run in the older container but fail on the updated one.

I think this is indeed worth more thought as the image list is grows.

**Pull request merged**
